version: "3.8"
services:
  api-server:
    restart: unless-stopped
    build:
      context: ./backend
    ports:
      - 5000:5000
  react-app:
    restart: unless-stopped
    build:
      context: ./frontend
    ports:
      - 80:80